### ISSUE TITLE
/me/email/confirm request builder is not working in browser environment

### ISSUE THREAD

**Issue by sfernengel** [commercetools/commercetools-sdk-typescript#452]
The following code works with node v18.15 on my machine, but the same piece of code gives an error in the Chrome browser (v111.0.5563.64 ) environment with the following SDK packages

```html
<script src="https://unpkg.com/@commercetools/sdk-client-v2@latest/dist/commercetools-sdk-client-v2.umd.js"></script>
<script src="https://unpkg.com/@commercetools/platform-sdk@latest/dist/commercetools-platform-sdk.umd.js"></script>
```

myApiRoot
        .me()
        .emailConfirm()
        .post({
            body: {
                tokenValue: "some valid token value"
            }
        })
        .execute();

The error I am getting in the browser is:
```commercetools-platform-sdk.umd.js:1 Uncaught TypeError: (0 , e.stringify) is not a function
    at i (commercetools-platform-sdk.umd.js:1:1470)
    at new e (commercetools-platform-sdk.umd.js:1:1814)
    at e.post (commercetools-platform-sdk.umd.js:1:98523)
    at confirmEmail (VerifyToken.js:46:6)
    at confirmEmail2 (VerifyToken.js:65:5)
    at onClick (VerifyToken.js:75:32)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (react-dom.development.js:9097:3)
    at eval (react-dom.development.js:9288:12)
    at batchedUpdates$1 (react-dom.development.js:26140:12)
    at batchedUpdates (react-dom.development.js:3991:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:3)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js:6465:5)
    at dispatchEvent (react-dom.development.js:6457:5)
    at dispatchDiscreteEvent (react-dom.development.js:6430:5)
```

**Root cause: the import of stringify from querystring package in UMD looks like this:**
```js
    var e = {
        305: ()=>{}
    }
```

**Comment by ajimae** [comment]
Hi @sfernengel 

Since this is related to `querystring` dependency see my comment in [here](https://github.com/commercetools/commercetools-sdk-typescript/issues/451#issuecomment-1482514154)

We will get it fixed and the fix should reflex in our next SDK release cycle.


Thanks

**Comment by anjaliVashisth** [comment]
The Fix is available in the TypeScript SDK. https://github.com/commercetools/commercetools-sdk-typescript/pull/453
